version: "3.6"

services: 
  database:
    container_name: postgre
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: ./etc/db/.env
    ports:
      - "5432:5432"

volumes:
  db-data:
